/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface MoveComponentOptionsSchema {
  project?: string;
  /**
   * The folder of the component source.
   */
  from?: string;
  /**
   * The target folder of the component.
   */
  to?: string;
}
