stages:
  - build
  - publish
  - deploy

build:
  stage: build
  tags:
  - docker-executor
  image: selenium/standalone-chrome
  script:
  - ./gradlew --no-daemon --max-workers 1 --continue -Dgeb.env=ci reset build
  - bash .gitlab-ci-test-universal.sh

.job-template: &job_definition
  stage: publish
  retry: 2
  only:
    refs:
      - develop
  tags:
  - shell-executor
  - docker
  script:
  - docker build -t ${CI_REGISTRY}/${CI_PROJECT_PATH}-${ENVIRONMENT}:${CI_BUILD_REF}
           --build-arg env=${ENVIRONMENT}
           --label environment="${ENVIRONMENT}"
           --label revision="${CI_BUILD_REF}"
           --label project="${CI_PROJECT_URL}"
           .
  - timeout 10m sh .gitlab-ci-wait-registry.sh
  - docker login -u ${BUILD_USER} -p ${BUILD_PASSWORD} ${CI_REGISTRY}
  - docker push ${CI_REGISTRY}/${CI_PROJECT_PATH}-${ENVIRONMENT}:${CI_BUILD_REF}

push_dev:
  <<: *job_definition
  variables:
    ENVIRONMENT: "dev"

push_prod:
  <<: *job_definition
  variables:
    ENVIRONMENT: "prod"

deploy_demo:
  stage: deploy
  only:
    refs:
      - develop
  tags:
  - shell-executor
  - docker
  - chuck-norris-swarm-manager
  script:
  - docker service rm poc || true
  - docker service create --replicas 10 --publish mode=host,target=4000,published=4321 --name poc ${CI_REGISTRY}/${CI_PROJECT_PATH}-dev:${CI_BUILD_REF}
