stages:
  - build
  - e2e
  - publish
  - deploy

build:
  stage: build
  except:
    refs:
      - develop
  tags:
  - docker-executor
  image: node:8-alpine
  script:
  - apk --no-cache add git
  - npm install
  - npm run test -- --ci
  - npm run lint
  - npm run build:dynamic:prod
  - npm run format
  - git status --porcelain | wc -l | xargs test '0' -eq

e2e:
  stage: e2e
  tags:
  - docker-executor
  image: 
    name: caltha/protractor
    entrypoint: [""]
  script:
  - apt-get update
  - apt-get install -y wget
  - npm install
  - npx webdriver-manager update --chrome --chrome.version=2.38 --gecko false
  - export ICM_BASE_URL="http://localhost:4000"
  - npm run build:dynamic
  - npm run serve:dynamic &
  - wget -q --wait 10 --tries 1000 --retry-connrefused http://localhost:4000
  - sh .gitlab-ci-test-universal.sh
  - npx protractor --capabilities.chromeOptions.args="--no-sandbox" --capabilities.chromeOptions.args="--headless" --baseUrl http://localhost:4000

.job-template: &job_definition
  stage: publish
  retry: 2
  only:
    refs:
      - develop
  tags:
  - shell-executor
  - docker
  script:
  - docker build -t ${CI_REGISTRY}/${CI_PROJECT_PATH}-${ENVIRONMENT}:${CI_BUILD_REF}
           --build-arg env=${ENVIRONMENT}
           --label environment="${ENVIRONMENT}"
           --label revision="${CI_BUILD_REF}"
           --label project="${CI_PROJECT_URL}"
           .
  - timeout 10m sh .gitlab-ci-wait-registry.sh
  - docker login -u ${BUILD_USER} -p ${BUILD_PASSWORD} ${CI_REGISTRY}
  - docker push ${CI_REGISTRY}/${CI_PROJECT_PATH}-${ENVIRONMENT}:${CI_BUILD_REF}
  - curl -v -X DELETE -u ${BUILD_USER}:${BUILD_PASSWORD} "http://rnd-repo.rnd.j.intershop.de/local-docker-dev/${CI_PROJECT_PATH}-${ENVIRONMENT}/latest"
  - curl -v -f -X POST -u ${BUILD_USER}:${BUILD_PASSWORD} "http://rnd-repo.rnd.j.intershop.de/api/copy/local-docker-snapshots/${CI_PROJECT_PATH}-${ENVIRONMENT}/${CI_BUILD_REF}?to=/local-docker-dev/${CI_PROJECT_PATH}-${ENVIRONMENT}/latest"

push_dev:
  <<: *job_definition
  variables:
    ENVIRONMENT: "dev"

push_prod:
  <<: *job_definition
  variables:
    ENVIRONMENT: "prod"

deploy_demo:
  stage: deploy
  only:
    refs:
      - develop
  tags:
  - shell-executor
  - docker
  - chuck-norris-swarm-manager
  script: bash .gitlab-ci-deploy.sh
  environment:
    name: demo
    url: http://jdevbuildslave01.rnd.j.intershop.de:4321
