stages:
  - mrconfig
  - setup
  - build
  - publish
  - deploy
  - e2e
  - verify

variables:
  npm_config_cache: '$CI_PROJECT_DIR/cache/.npm'
  CYPRESS_CACHE_FOLDER: '$CI_PROJECT_DIR/cache/Cypress'

cache:
  key: ${CI_COMMIT_REF_SLUG}
  untracked: false
  paths:
    - cache

cancel_old_pipelines:
  cache: {}
  dependencies: []
  image: endeveit/docker-jq
  stage: mrconfig
  only:
    - merge_requests
  tags:
    - docker-executor
  script:
    - sh .gitlab-ci-cancel-old-pipelines.sh
    - echo "cancel complete"

setup:
  image: node:10
  stage: setup
  only:
    - merge_requests
  except:
    refs:
      - develop
      - master
  tags:
    - docker-executor
  script:
    - node --version && npm --version
    - bash -c "cd tslint-rules ; npm --silent run build"
    - bash .gitlab-ci-test-no-changes.sh 'you probably did not commit compiled binaries in tslint-rules'
    - bash -c "cd schematics ; npm --silent run build"
    - bash .gitlab-ci-test-no-changes.sh 'you probably did not commit compiled binaries in schematics'
    - npm ci --prefer-offline
    - bash .gitlab-ci-test-no-changes.sh 'you probably did not commit package-lock.json after installing packages'
    - echo "setup complete"

jest_test:
  image: node:10
  stage: build
  only:
    - merge_requests
  except:
    refs:
      - develop
      - master
  tags:
    - docker-executor
  artifacts:
    paths:
      - reports/coverage
    expire_in: 1 day
    reports:
      junit: reports/junit.xml
  dependencies: []
  coverage: '/^Statements\s*:\s*([^%]+)/'
  script:
    - npm ci --prefer-offline
    - npx jest -c jest-reports.config.js --ci
    - echo "build complete"

compile:
  image: node:10
  stage: build
  only:
    - merge_requests
  except:
    refs:
      - develop
      - master
  tags:
    - docker-executor
  artifacts:
    paths:
      - reports/bundle
    expire_in: 1 day
  dependencies: []
  script:
    - npm ci --prefer-offline --production
    - npx ng build --progress false --prod --stats-json
    - npx webpack-bundle-analyzer dist/browser/stats.json dist/browser -r reports/bundle/index.html -m static
    - npm ci --prefer-offline
    - npx tsc -p src/tsconfig.spec.json
    - echo "build complete"

codestyle:
  image: node:10
  stage: build
  only:
    - merge_requests
  except:
    refs:
      - develop
      - master
  tags:
    - docker-executor
  artifacts:
    expire_in: 1 day
    paths:
      - reports/jscpd
      - reports/tslint
  dependencies: []
  script:
    - npm ci --prefer-offline
    - npm i --no-save tslint-html-report jscpd-html-reporter
    - node reports/tslint-report
    - node reports/jscpd-report
    - npm run lint -- --format stylish
    - npm run format
    - bash .gitlab-ci-test-no-changes.sh 'you probably committed unformatted code'
    - echo "build complete"

cypress_mocked:
  image: cypress/browsers:chrome69
  stage: build
  only:
    - merge_requests
  except:
    refs:
      - develop
      - master
  tags:
    - docker-executor
  artifacts:
    reports:
      junit: reports/e2e-*.xml
    when: on_failure
    expire_in: 2 weeks
    paths:
      - cypress/screenshots
  dependencies: []
  script:
    - node --version && npm --version
    - npm i
    - export ICM_BASE_URL=http://localhost:4200 PWA_BASE_URL=http://localhost:4200 DISPLAY=:5
    - nohup bash -c "Xvfb ${DISPLAY} &"
    - nohup bash -c "npx ng serve &"
    - wget -q --wait 10 --tries 10 --retry-connrefused http://localhost:4200
    - find $PWD -name '*mock*.e2e-spec.ts' | xargs -rl sh .gitlab-ci-test-e2e.sh
    - echo "E2E complete"

publish_pwa:
  cache: {}
  dependencies: []
  image: docker:stable
  stage: build
  only:
    refs:
      - develop
      - tags
      - merge_requests
  tags:
    - shell-executor
    - docker
    - performance
  services:
    - docker:dind
  script:
    - VERSION="$(grep "version" package.json | grep -Eo '[0-9][^"]*')"
    - docker info --format '{{json .Name}}' || (export DOCKER_HOST=tcp://localhost:2375/ DOCKER_DRIVER=overlay2 && docker info --format '{{json .Name}}') || (export DOCKER_HOST=tcp://docker:2375/ DOCKER_DRIVER=overlay2 && docker info --format '{{json .Name}}')
    - docker build -t ${CI_REGISTRY_IMAGE}:${CI_BUILD_REF}
      --build-arg displayVersion="$VERSION ($CI_COMMIT_REF_NAME @ $CI_COMMIT_SHA)"
      --label environment="production"
      --label revision="${CI_BUILD_REF}"
      --label project="${CI_PROJECT_URL}"
      .
    - test -z "${CI_JOB_TOKEN}" || docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - test -z "${CI_JOB_TOKEN}" || docker push ${CI_REGISTRY_IMAGE}:${CI_BUILD_REF}
    - test -z "${CI_JOB_TOKEN}" || docker tag ${CI_REGISTRY_IMAGE}:${CI_BUILD_REF} ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}
    - test -z "${CI_JOB_TOKEN}" || docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}

publish_pwa_latest:
  cache: {}
  dependencies: []
  image: docker:stable
  stage: publish
  only:
    - tags
  tags:
    - docker-executor
  services:
    - docker:dind
  script:
    - docker info --format '{{json .Name}}' || (export DOCKER_HOST=tcp://localhost:2375/ DOCKER_DRIVER=overlay2 && docker info --format '{{json .Name}}') || (export DOCKER_HOST=tcp://docker:2375/ DOCKER_DRIVER=overlay2 && docker info --format '{{json .Name}}')
    - test -z "${CI_JOB_TOKEN}" || docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - test -z "${CI_JOB_TOKEN}" || docker pull ${CI_REGISTRY_IMAGE}:${CI_BUILD_REF}
    - test -z "${CI_JOB_TOKEN}" || docker tag ${CI_REGISTRY_IMAGE}:${CI_BUILD_REF} ${CI_REGISTRY_IMAGE}:latest
    - test -z "${CI_JOB_TOKEN}" || docker push ${CI_REGISTRY_IMAGE}:latest

start_nginx_proxy:
  cache: {}
  dependencies: []
  stage: publish
  only:
    - merge_requests
  tags:
    - shell-executor
    - docker
    - demoserver
  script:
    - docker run --restart always --detach -p 4199:80 -v /var/run/docker.sock:/tmp/docker.sock:ro jwilder/nginx-proxy || true

publish_nginx:
  cache: {}
  dependencies: []
  image: docker:stable
  stage: publish
  only:
    refs:
      - develop
      - master
      - tags
      - merge_requests
  tags:
    - shell-executor
    - docker
    - performance
  services:
    - docker:dind
  variables:
    CI_DEBUG_TRACE: 'true'
  script:
    - docker info --format '{{json .Name}}' || (export DOCKER_HOST=tcp://localhost:2375/ DOCKER_DRIVER=overlay2 && docker info --format '{{json .Name}}') || (export DOCKER_HOST=tcp://docker:2375/ DOCKER_DRIVER=overlay2 && docker info --format '{{json .Name}}')
    - test -z "${CI_JOB_TOKEN}" || docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - docker build -t ${CI_REGISTRY_IMAGE}:nginx-${CI_COMMIT_REF_SLUG} nginx
    - test -z "${CI_JOB_TOKEN}" || docker push ${CI_REGISTRY_IMAGE}:nginx-${CI_COMMIT_REF_SLUG}

push_reports:
  stage: publish
  cache: {}
  only:
    refs:
      - develop
  allow_failure: true
  tags:
    - shell-executor
    - docker
    - performance
  script:
    - docker build -t ${CI_REGISTRY_IMAGE}:reports
      --build-arg ICM_BASE_URL=${ICM_BASE_URL}
      --label revision="${CI_BUILD_REF}"
      --label project="${CI_PROJECT_URL}"
      --file Dockerfile_reports
      .
    - test -z "${CI_JOB_TOKEN}" || docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - docker push ${CI_REGISTRY_IMAGE}:reports

deploy_demo:
  stage: deploy
  cache: {}
  dependencies: []
  only:
    refs:
      - develop
  tags:
    - shell-executor
    - docker
    - demoserver
  variables:
    GIT_STRATEGY: none
    SERVICE: 'intershop-pwa'
    IMAGE: '${CI_REGISTRY_IMAGE}:${CI_BUILD_REF}'
  script:
    - test -z "${CI_JOB_TOKEN}" || docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - docker rm -f ${SERVICE} || true
    - docker run
      --detach
      --restart always
      --publish 4321:4200
      --name ${SERVICE}
      --env ICM_BASE_URL=$ICM_BASE_URL
      --env LOGGING=true
      --env SENTRY_DSN=${SENTRY_DSN}
      ${IMAGE}
  environment:
    name: demo
    url: http://$DEMO_SERVER_NAME:4321

deploy_demo_b2b:
  stage: deploy
  cache: {}
  dependencies: []
  only:
    refs:
      - develop
  tags:
    - shell-executor
    - docker
    - demoserver
  variables:
    GIT_STRATEGY: none
    SERVICE: 'intershop-pwa-b2b'
    IMAGE: '${CI_REGISTRY_IMAGE}:${CI_BUILD_REF}'
  script:
    - test -z "${CI_JOB_TOKEN}" || docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - docker rm -f ${SERVICE} || true
    - docker run
      --detach
      --restart always
      --publish 4325:4200
      --name ${SERVICE}
      --env ICM_BASE_URL=$ICM_BASE_URL
      --env LOGGING=true
      --env FEATURES=quoting,compare,recently,businessCustomerRegistration,sentry
      --env ICM_CHANNEL=inSPIRED-inTRONICS_Business-Site
      --env SENTRY_DSN=${SENTRY_DSN}
      ${IMAGE}
  environment:
    name: demo-b2b
    url: http://$DEMO_SERVER_NAME:4325

deploy_demo_BO:
  stage: deploy
  cache: {}
  dependencies: []
  tags:
    - shell-executor
  only:
    - merge_requests
    - develop
  variables:
    GIT_STRATEGY: none
  script:
    - echo "done"
  environment:
    name: BackOffice
    url: $BO_URL

deploy_reports:
  stage: deploy
  cache: {}
  dependencies: []
  only:
    refs:
      - develop
  allow_failure: true
  tags:
    - shell-executor
    - docker
    - demoserver
  variables:
    GIT_STRATEGY: none
    SERVICE: 'intershop-pwa-reports'
    IMAGE: '${CI_REGISTRY_IMAGE}:reports'
  script:
    - test -z "${CI_JOB_TOKEN}" || docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - docker rm -f ${SERVICE} || true
    - docker run
      --detach
      --restart always
      --publish 4324:8080
      --name ${SERVICE}
      ${IMAGE}
  environment:
    name: reports
    url: http://$DEMO_SERVER_NAME:4324

deploy_review_b2c:
  stage: deploy
  cache: {}
  dependencies: []
  tags:
    - shell-executor
  only:
    - merge_requests
  variables:
    GIT_STRATEGY: none
  script:
    - echo "done"
  environment:
    name: review/b2c-$CI_COMMIT_REF_SLUG
    url: http://b2c.$CI_COMMIT_REF_SLUG.$DEMO_SERVER_NAME:4199
    on_stop: stop_review_b2c

stop_review_b2c:
  stage: deploy
  cache: {}
  dependencies: []
  when: manual
  tags:
    - shell-executor
  only:
    - merge_requests
  variables:
    GIT_STRATEGY: none
  script:
    - echo "done"
  environment:
    name: review/b2c-$CI_COMMIT_REF_SLUG
    action: stop

deploy_review_b2b:
  stage: deploy
  retry: 2
  cache: {}
  dependencies: []
  tags:
    - shell-executor
    - docker
    - demoserver
  only:
    - merge_requests
  variables:
    GIT_STRATEGY: none
  script:
    - set -x
    - test -z "${CI_JOB_TOKEN}" || docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - docker rm -f "${CI_COMMIT_REF_SLUG}-pwa" || true
    - docker pull ${CI_REGISTRY_IMAGE}:${CI_BUILD_REF}
    - docker run
      --detach
      --name "${CI_COMMIT_REF_SLUG}-pwa"
      -e LOGGING=true
      -e SENTRY_DSN=${SENTRY_DSN}
      -e ICM_BASE_URL=${ICM_BASE_URL}
      --add-host b2b.$CI_COMMIT_REF_SLUG.$DEMO_SERVER_NAME:$(dig ${DNS_SERVER} +short $DEMO_SERVER_NAME)
      --add-host b2c.$CI_COMMIT_REF_SLUG.$DEMO_SERVER_NAME:$(dig ${DNS_SERVER} +short $DEMO_SERVER_NAME)
      --add-host de.$CI_COMMIT_REF_SLUG.$DEMO_SERVER_NAME:$(dig ${DNS_SERVER} +short $DEMO_SERVER_NAME)
      --add-host smb.$CI_COMMIT_REF_SLUG.$DEMO_SERVER_NAME:$(dig ${DNS_SERVER} +short $DEMO_SERVER_NAME)
      ${CI_REGISTRY_IMAGE}:${CI_BUILD_REF}
    - docker rm -f "${CI_COMMIT_REF_SLUG}-nginx" || true
    - docker pull ${CI_REGISTRY_IMAGE}:nginx-${CI_COMMIT_REF_SLUG}
    - docker run
      --detach
      --name "${CI_COMMIT_REF_SLUG}-nginx"
      -e UPSTREAM_ICM=${ICM_BASE_URL}
      --link $CI_COMMIT_REF_SLUG-pwa
      -e UPSTREAM_PWA=http://$CI_COMMIT_REF_SLUG-pwa:4200
      -e PWA_1_SUBDOMAIN=b2b
      -e PWA_1_CHANNEL=inSPIRED-inTRONICS_Business-Site
      -e PWA_1_FEATURES=quoting,recently,compare,businessCustomerRegistration,sentry
      -e PWA_2_SUBDOMAIN=b2c
      -e PWA_2_CHANNEL=inSPIRED-inTRONICS-Site
      -e PWA_3_SUBDOMAIN=de
      -e PWA_3_CHANNEL=inSPIRED-inTRONICS-Site
      -e PWA_3_LANG=de_DE
      -e PWA_3_FEATURES=none
      -e PWA_4_SUBDOMAIN=smb
      -e PWA_4_CHANNEL=inSPIRED-inTRONICS-Site
      -e PWA_4_APPLICATION=smb-responsive
      -e PWA_4_FEATURES=quoting
      -e VIRTUAL_HOST=b2c.$CI_COMMIT_REF_SLUG.$DEMO_SERVER_NAME,b2b.$CI_COMMIT_REF_SLUG.$DEMO_SERVER_NAME,de.$CI_COMMIT_REF_SLUG.$DEMO_SERVER_NAME,smb.$CI_COMMIT_REF_SLUG.$DEMO_SERVER_NAME
      ${CI_REGISTRY_IMAGE}:nginx-${CI_COMMIT_REF_SLUG}
    - sleep 10
    - docker run --rm --add-host b2b.$CI_COMMIT_REF_SLUG.$DEMO_SERVER_NAME:$(dig ${DNS_SERVER} +short $DEMO_SERVER_NAME) mwendler/wget --wait 10 --tries 10 --retry-connrefused "http://b2b.$CI_COMMIT_REF_SLUG.$DEMO_SERVER_NAME:4199"
    - docker run --rm --add-host b2c.$CI_COMMIT_REF_SLUG.$DEMO_SERVER_NAME:$(dig ${DNS_SERVER} +short $DEMO_SERVER_NAME) mwendler/wget --wait 10 --tries 10 --retry-connrefused "http://b2c.$CI_COMMIT_REF_SLUG.$DEMO_SERVER_NAME:4199"
  environment:
    name: review/b2b-$CI_COMMIT_REF_SLUG
    url: http://b2b.$CI_COMMIT_REF_SLUG.$DEMO_SERVER_NAME:4199
    on_stop: stop_review_b2b

stop_review_b2b:
  stage: deploy
  cache: {}
  dependencies: []
  when: manual
  tags:
    - shell-executor
    - docker
    - demoserver
  only:
    - merge_requests
  variables:
    GIT_STRATEGY: none
  script:
    - docker rm -f "${CI_COMMIT_REF_SLUG}-pwa" || true
    - docker rm -f "${CI_COMMIT_REF_SLUG}-nginx" || true
  environment:
    name: review/b2b-$CI_COMMIT_REF_SLUG
    action: stop

schematics:
  image: node:10
  stage: e2e
  only:
    - merge_requests
  except:
    refs:
      - develop
      - master
  tags:
    - docker-executor
  dependencies: []
  script:
    - npm install
    - bash .gitlab-ci-test-schematics.sh
    - echo "schematics complete"

cypress_remote:
  image: cypress/browsers:chrome69
  stage: e2e
  only:
    - merge_requests
    - triggers
  tags:
    - docker-executor
  artifacts:
    reports:
      junit: reports/e2e-*.xml
    when: on_failure
    expire_in: 2 weeks
    paths:
      - cypress/screenshots
  dependencies: []
  script:
    - set -x
    - apt-get update || true
    - apt-get -y install dnsutils
    - node --version && npm --version
    - export DISPLAY=:5
    - test $CI_PIPELINE_SOURCE = trigger && export PWA_BASE_URL=http://$DEMO_SERVER_NAME:4321 || export PWA_BASE_URL=http://b2c.$CI_COMMIT_REF_SLUG.$DEMO_SERVER_NAME:4199
    - export CYPRESS_NO_CHANNEL_REDIRECT=1
    - npm i
    - wget --wait 10 --tries 30 --retry-connrefused ${ICM_BASE_URL}/INTERSHOP/rest/WFS/inSPIRED-inTRONICS-Site/-
    - test $CI_PIPELINE_SOURCE = trigger || echo "$(dig ${DNS_SERVER} +short $DEMO_SERVER_NAME) b2c.$CI_COMMIT_REF_SLUG.$DEMO_SERVER_NAME" >> /etc/hosts
    - wget --wait 10 --tries 10 --retry-connrefused ${PWA_BASE_URL}
    - sh .gitlab-ci-test-universal.sh
    - nohup bash -c "Xvfb ${DISPLAY} &"
    - find $PWD -name '*b2c*.e2e-spec.ts' | xargs -rl sh .gitlab-ci-test-e2e.sh
    - echo "E2E complete"

cypress_remote_b2b:
  image: cypress/browsers:chrome69
  stage: e2e
  only:
    - merge_requests
    - triggers
  tags:
    - docker-executor
  artifacts:
    reports:
      junit: reports/e2e-*.xml
    when: on_failure
    expire_in: 2 weeks
    paths:
      - cypress/screenshots
  dependencies: []
  script:
    - set -x
    - apt-get update || true
    - apt-get -y install dnsutils
    - node --version && npm --version
    - export DISPLAY=:5
    - test $CI_PIPELINE_SOURCE = trigger && export PWA_BASE_URL=http://$DEMO_SERVER_NAME:4325 || export PWA_BASE_URL=http://b2b.$CI_COMMIT_REF_SLUG.$DEMO_SERVER_NAME:4199
    - export CYPRESS_NO_CHANNEL_REDIRECT=1
    - npm i
    - wget --wait 10 --tries 30 --retry-connrefused ${ICM_BASE_URL}/INTERSHOP/rest/WFS/inSPIRED-inTRONICS_Business-Site/-
    - test $CI_PIPELINE_SOURCE = trigger || echo "$(dig ${DNS_SERVER} +short $DEMO_SERVER_NAME) b2b.$CI_COMMIT_REF_SLUG.$DEMO_SERVER_NAME" >> /etc/hosts
    - wget --wait 10 --tries 10 --retry-connrefused ${PWA_BASE_URL}
    - sh .gitlab-ci-test-universal.sh
    - nohup bash -c "Xvfb ${DISPLAY} &"
    - find $PWD -name '*b2b*.e2e-spec.ts' | xargs -rl sh .gitlab-ci-test-e2e.sh
    - echo "E2E complete"

check_mr_title:
  cache: {}
  dependencies: []
  image: endeveit/docker-jq
  stage: verify
  only:
    - merge_requests
  tags:
    - docker-executor
  script:
    - sh .gitlab-ci-check-mr-title.sh
    - echo "check complete"
