# export appropriate ICM_BASE_URL and use with
# docker compose up --build

services:
  pwa:
    image: intershophub/intershop-pwa-ssr
    build:
      context: .
      # args:
      #   activeThemes: b2b
      #   activeThemes: b2c
    # command: ['node', 'dist/b2c/run-standalone']
    # command: ['node', 'dist/b2b/run-standalone']
    # ports:
    #   - '4201:4200'
    #   - '9113:9113'
    environment:
      ICM_BASE_URL: 'https://develop.icm.intershop.de'
      # additional host names the SSR server accepts besides 'localhost'
      # ALLOWED_HOSTS: 'shop.example.com,*.example.com'
      # TRUST_ICM: 'true'
      # LOGLEVEL: 'info' # trace, debug, info, warn, error, fatal - default: error
      # LOGFORMAT: 'text' # text, json - default: json (ECS-compatible)
      SOURCE_MAPS: 'true'
      # SSR_HYBRID: 'true'
      # PROXY_ICM: 'true'
      # PROMETHEUS: 'true'
      # METRICS_DETAIL_LEVEL: 'DETAILED'
      # MULTI_SITE_LOCALE_MAP: |
      #   en_US: /en
      #   de_DE: /de
      #   fr_FR: /fr
      # FEATURES: |
      #   - compare
      #   - rating
      # IDENTITY_PROVIDER: 'Auth0'
      IDENTITY_PROVIDERS: |
        Punchout:
          type: PUNCHOUT
        CoBrowse:
          type: cobrowse
      #   Auth0:
      #     type: auth0
      #     domain: some-domain.auth0.com
      #     clientID: ASDF12345
      #
      # allow backend requests to use HTTP/2 with Fetch API (experimental)
      # ALLOW_H2: 'true'

  nginx:
    image: intershophub/intershop-pwa-nginx
    build: nginx
    depends_on:
      - pwa
    ports:
      - '4200:80'
      # - '9114:9113'
      # - '443:443'
    environment:
      UPSTREAM_PWA: 'http://pwa:4200'
      ICM_BASE_URL: 'https://develop.icm.intershop.de'
      NGINX_ENTRYPOINT_QUIET_LOGS: ANYVALUE
      CACHE: 0
      # CACHE_CLEARER: 0 # Cache clearing is enabled by default when CACHE=1; set to 0 to disable cache clearer based on ICM webadapter statistics
      # LOGLEVEL: 'info' # info (all), warn (4xx+5xx), error (5xx) - default: error
      # LOGFORMAT: 'text' # text, json - default: json (ECS-compatible)
      # SSL: 1
      # SSR: 0
      # DEBUG: 1
      # PROMETHEUS: 1
      # COMPRESSION: 0
      # DEVICE_DETECTION: 0
      # CACHING_IGNORE_PARAMS: |
      #   params:
      OVERRIDE_IDENTITY_PROVIDERS: |
        .+:
          - path: /punchout
            type: Punchout
          - path: /cobrowse
            type: CoBrowse
      # MULTI_CHANNEL_SOURCE: env:///ASDF?type=application/yaml
      MULTI_CHANNEL: |
        .+:
          - baseHref: /en
            channel: inSPIRED-inTRONICS_Business-Site
            lang: en_US
          - baseHref: /de
            channel: inSPIRED-inTRONICS_Business-Site
            lang: de_DE
          - baseHref: /fr
            channel: inSPIRED-inTRONICS_Business-Site
            lang: fr_FR
          - baseHref: /b2c
            channel: inSPIRED-inTRONICS-Site
            theme: b2c
      # ADDITIONAL_HEADERS: |
      #   headers:
      #     - Content-Security-Policy: "default-src https://develop.icm.intershop.de 'self'; style-src 'unsafe-inline' 'self'; font-src data: 'self'; script-src secure.pay1.de 'self'; frame-src secure.pay1.de;"
      #     - X-Frame-Options: 'SAMEORIGIN'
      # REDIS_URI: redis://redis:6379

    # Provide own SSL certificate files with SSL enabled (see nginx-startup.md)
    # volumes:
    #   - <LOCAL_PATH>/fullchain.pem:/var/nginx/certs/cert.pem
    #   - <LOCAL_PATH>/privkey.pem:/var/nginx/certs/key.pem

  # <CDN-Example>
  # - add 127.0.0.1 mypwa.net to your hosts file and
  # - add DEPLOY_URL: 'http://mypwa.net:4222' to the pwa environment section
  # - uncomment the following lines
  #
  # cdn:
  #   build:
  #     context: .
  #     args:
  #       configuration: production
  #       deployUrl: http://mypwa.net:4222
  #   ports:
  #     - '4222:4200'
  #
  # </CDN-Example>

  # redis:
  #   image: bitnami/redis
  #   container_name: redis
  #   environment:
  #     - ALLOW_EMPTY_PASSWORD=yes
