FROM caltha/protractor
RUN apt-get update
RUN apt-get install -y wget
COPY package.json package-lock.json /workspace/
WORKDIR /workspace
RUN npm install
RUN npx webdriver-manager update --chrome --chrome.version=2.38 --gecko false
ENV ICM_BASE_URL="http://localhost:4000"
COPY . /workspace/
RUN npm run build:dynamic
RUN (npm run serve:dynamic&) \
 && wget -q --wait 10 --tries 30 --retry-connrefused http://localhost:4000 \
 && sh .gitlab-ci-test-universal.sh \
 && npx protractor --capabilities.chromeOptions.args="--no-sandbox" --capabilities.chromeOptions.args="--headless" --baseUrl http://localhost:4000
