FROM cypress/browsers:chrome67
COPY package.json package-lock.json /workspace/
COPY tslint-rules /workspace/tslint-rules/
WORKDIR /workspace
RUN npm install | grep -v 'title changed'
ARG ICM_BASE_URL="http://localhost:4200"
COPY . /workspace/
RUN npm run build:dynamic:prod
RUN echo ICM_BASE_URL=${ICM_BASE_URL}
RUN nohup bash -c "Xvfb :5 &" \
 && export DISPLAY=:5 \
 && nohup bash -c "npm run serve:dynamic &" \
 && wget -q --wait 10 --tries 30 --retry-connrefused http://localhost:4200 \
 && sh .gitlab-ci-test-universal.sh \
 && npx cypress run -b chrome -e ICM_BASE_URL=${ICM_BASE_URL} -c "baseUrl=http://localhost:4200" \
 && nohup bash -c "npx ng serve --aot --progress false --port 4400 &" \
 && wget -q --wait 10 --tries 30 --retry-connrefused http://localhost:4400 \
 && npx cypress run -b chrome -e ICM_BASE_URL=${ICM_BASE_URL} -c "baseUrl=http://localhost:4400,integrationFolder=cypress/integration/local"
