FROM node:14-alpine as buildstep
WORKDIR /workspace
COPY schematics /workspace/schematics/
COPY package.json package-lock.json /workspace/
RUN npm i --ignore-scripts
COPY projects/organization-management/src/app /workspace/projects/organization-management/src/app/
COPY projects/requisition-management/src/app /workspace/projects/requisition-management/src/app/
COPY src /workspace/src/
COPY tsconfig.app.json tsconfig.base.json ngsw-config.json .browserslistrc angular.json /workspace/
RUN npm run build:schematics && npm run synchronize-lazy-components -- --ci
ARG configuration=production
COPY scripts /workspace/scripts/
RUN test "${configuration}" = 'local' && node scripts/init-local-environment.js || true
ARG serviceWorker
RUN node schematics/customization/service-worker ${serviceWorker} || true
COPY templates/production/* /workspace/templates/production/
RUN npm run ng -- build -c ${configuration}

# ^ this part above is copied from the standard Dockerfile and should be kept in sync

FROM nginx:alpine
COPY templates/nginx.conf /etc/nginx/nginx.conf
COPY --from=buildstep /workspace/dist/browser /usr/share/nginx/html
EXPOSE 4200
