# To build this report image, you will have to temporarily truncate the .dockerignore

# synchronize-marker:docker-cache-share:begin
FROM node:22.22.0-alpine AS buildstep
# increase the `--max-old-space-size` if "FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory" occur during build
ENV NODE_OPTIONS=--max-old-space-size=8192
ENV CI=true
WORKDIR /workspace
COPY package.json package-lock.json /workspace/
RUN npm ci --prefer-offline --no-audit --ignore-scripts
RUN find node_modules -path '*/esbuild/install.js' | xargs -rt -n 1 node
# synchronize-marker:docker-cache-share:end
COPY . /workspace/
RUN npm run postinstall
RUN npm i --no-save jest-html-reporter jest-junit && npx jest -c jest-reports.config.ts --ci --testFailureExitCode 0
RUN npx license-checker --csv --out reports/licenses/licenses.csv --customPath templates/3rd-party-licenses_format.json && npm i --no-save htmlify-csv && node node_modules/htmlify-csv/htmlify-csv convert reports/licenses/licenses.csv --output reports/licenses/index.html
RUN npm i --no-save jscpd-html-reporter && node reports/jscpd-report
RUN npm i -g webpack-bundle-analyzer
RUN rm -Rf dist && npm run build client -- --progress false --stats-json && webpack-bundle-analyzer dist/browser/stats.json dist/browser -r reports/bundle_prod/index.html -m static

FROM danjellz/http-server
COPY --from=buildstep /workspace/reports /public
COPY --from=buildstep /workspace/docs /public/docs
