# synchronize-marker:pwa-docker-build:begin
FROM node:14-alpine as buildstep
WORKDIR /workspace
COPY package.json package-lock.json /workspace/
RUN npm i --ignore-scripts
RUN npm run ngcc
COPY tsconfig.app.json tsconfig.json ngsw-config.json .browserslistrc angular.json tslint.json /workspace/
COPY tslint-rules /workspace/tslint-rules
COPY schematics /workspace/schematics
COPY projects /workspace/projects
COPY src /workspace/src
COPY scripts /workspace/scripts/
RUN npm run postinstall
ARG serviceWorker
RUN node schematics/customization/service-worker ${serviceWorker} || true
COPY templates/webpack/* /workspace/templates/webpack/
ARG testing=false
ENV TESTING=${testing}
# synchronize-marker:pwa-docker-build:end

# ^ this part above is copied from the standard Dockerfile and should be kept in sync

ARG configuration=
RUN npm run build client --configuration=${configuration} -- --deploy-url=DEPLOY_URL_PLACEHOLDER
ARG deployUrl=/
RUN npx ts-node scripts/set-deploy-url ${deployUrl}

FROM nginx:alpine
COPY templates/nginx.conf /etc/nginx/nginx.conf
COPY --from=buildstep /workspace/dist/browser /usr/share/nginx/html
EXPOSE 4200
