import { Environment } from './environment.model';

/**
 * Do not edit this file, it will always be exchanged with
 * a theme-specific environment file
 *
 * This file should also not provide any properties,
 * otherwise tests will be polluted with them
 */

// eslint-disable-next-line ish-custom-rules/no-object-literal-type-assertion
export const environment = {} as Environment;
