/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface PwaModelOptionsSchema {
  path?: string;
  tsext?: string;
  project?: string;
  restricted?: boolean;
  /**
   * The name of the model.
   */
  name?: string;
  /**
   * Flag to indicate if a simple model without helper and mapper should be created.
   */
  simple?: boolean;
  /**
   * The extension to generate the model in. If empty it is generated in the project core.
   */
  extension?: string;
}
