trigger:
  - develop
  - master
  - 'refs/tags/release-*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: registryServerName
    value: $(registryName).azurecr.io
  - group: acr_ishpwa

stages:
  - stage: init
    displayName: 'Prepare variables'
    jobs:
      - job: tag
        displayName: 'set tag variable'
        steps:
          - bash: |
              echo -n "##vso[task.setvariable variable=tag;isOutput=true]"
              if [[ $(Build.SourceBranch) =~ tags/(.*) ]]
              then
                echo ${BASH_REMATCH[1]}
              else
                echo $(build.buildId)
              fi
            name: setvarStep
      - job: imageName
        displayName: 'set imageBaseName variable'
        steps:
          - bash: |
              echo -n "##vso[task.setvariable variable=imageName;isOutput=true]"
              if [[ $(Build.SourceBranch) =~ tags/(.*) ]]
              then
                printf '%.5s-%.18s\n' $(echo $(System.CollectionUri) | sed -e 's/^https:\/\/dev.azure.com\/ish-//') $(System.TeamProject)
              else
                printf '%.5s-%.9s-%.8s\n' $(echo $(System.CollectionUri) | sed -e 's/^https:\/\/dev.azure.com\/ish-//') $(System.TeamProject) $(Build.SourceBranchName)
              fi
            name: setvarStep2

  - stage: ssr
    displayName: 'Build the SSR container'
    dependsOn: init
    jobs:
      - job: build_ssr
        displayName: 'docker build ssr'
        variables:
          - name: tag
            value: $[ stageDependencies.init.tag.outputs['setvarStep.tag'] ]
          - name: imageBaseName
            value: $[ stageDependencies.init.imageName.outputs['setvarStep2.imageName'] ]
          - name: imageName
            value: $(imageBaseName)-ssr
        steps:
          - bash: |
              docker build -f $(system.defaultWorkingDirectory)/Dockerfile -t $(registryServerName)/$(imageName):$(tag) $(system.defaultWorkingDirectory) --build-arg displayVersion=$(tag)
              docker login $(registryServerName) -u $(registryLogin) -p $(registryPassword)
              docker push $(registryServerName)/$(imageName):$(tag)

  - stage: nginx
    displayName: 'Build the nginx container'
    dependsOn: init
    jobs:
      - job: build_nginx
        displayName: 'docker build nginx'
        variables:
          - name: tag
            value: $[ stageDependencies.init.tag.outputs['setvarStep.tag'] ]
          - name: imageBaseName
            value: $[ stageDependencies.init.imageName.outputs['setvarStep2.imageName'] ]
          - name: imageName
            value: $(imageBaseName)-nginx
        steps:
          - bash: |
              docker build -f $(system.defaultWorkingDirectory)/nginx/Dockerfile -t $(registryServerName)/$(imageName):$(tag) $(system.defaultWorkingDirectory)/nginx
              docker login $(registryServerName) -u $(registryLogin) -p $(registryPassword)
              docker push $(registryServerName)/$(imageName):$(tag)
