/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Creates a new CMS component.
 */
export interface PwaCmsComponentOptionsSchema {
  path?: string;
  tsext?: string;
  artifactFolder?: boolean;
  artifactName?: string;
  project?: string;
  prefix?: string;
  styleext?: string;
  selector?: string;
  module?: string;
  skipImport?: boolean;
  export?: boolean;
  entryComponent?: boolean;
  restricted?: boolean;
  /**
   * The name of the component.
   */
  name?: string;
  /**
   * The name of the ICM model component.
   */
  definitionQualifiedName?: string;
  /**
   * When true, generates and includes a style file for the component.
   */
  styleFile?: boolean;
  /**
   * Flag to indicate if a dir is created.
   */
  flat?: boolean;
  /**
   * Flag to indicate if CMS prefixes should not be added.
   */
  noCMSPrefixing?: boolean;
}
