/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface PwaModuleOptionsSchema {
  path?: string;
  tsext?: string;
  project?: string;
  /**
   * The name of the module.
   */
  name?: string;
  /**
   * Flag to indicate if a dir is created.
   */
  flat?: boolean;
}
