/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Creates a new presentational component.
 */
export interface PwaComponentOptionsSchema {
  path?: string;
  tsext?: string;
  artifactFolder?: boolean;
  project?: string;
  prefix?: string;
  styleext?: string;
  selector?: string;
  module?: string;
  /**
   * The name of the component.
   */
  name?: string;
  /**
   * When true, generates and includes a style file for the component.
   */
  styleFile?: boolean;
  /**
   * Flag to indicate if a dir is created.
   */
  flat?: boolean;
  /**
   * When true, does not import this component into the owning NgModule.
   */
  skipImport?: boolean;
  /**
   * When true, the declaring NgModule exports this component.
   */
  export?: boolean;
  /**
   * When true, the new component is the entry component of the declaring NgModule.
   */
  entryComponent?: boolean;
}
