/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface PwaServiceOptionsSchema {
  path?: string;
  restricted?: boolean;
  tsext?: string;
  project?: string;
  /**
   * The name of the service.
   */
  name?: string;
  /**
   * The extension to generate the service in. If empty it is generated in core.
   */
  extension?: string;
}
