# LOGLEVEL=error: Set log level threshold to error (log errors only)
# Combined with LOG_ALL, this determines final logging behavior
# Only 5xx responses are logged
map $status $loglevel_loggable {
    ~^5     1;
    default 0;
}
