{
 "title": "PWA",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "nginx Requests 2m Window",
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(nginx_http_requests_total{job=\"pwa-nginx\"}[2m]))"
    }
   ]
  },
  {
   "title": "nginx Instances",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(nginx_up{job=\"pwa-nginx\"})"
    }
   ]
  },
  {
   "title": "SSR Requests 2m Window",
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_sum{job=\"pwa-ssr\"}[2m]))"
    }
   ]
  },
  {
   "title": "SSR Instances",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"pwa-ssr\"})"
    }
   ]
  },
  {
   "title": "SSR Mean Render Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{job=\"pwa-ssr\"}[5m])) by (le))"
    }
   ]
  },
  {
   "title": "SSR Status >=500",
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{job=\"pwa-ssr\",status_code=~\"5[0-9][0-9]\"}[1m]))"
    }
   ]
  }
 ]
}