FROM node:14 as buildstep
COPY . /workspace/
WORKDIR /workspace
RUN npm ci
RUN ./node_modules/.bin/ngcc
RUN npm run build:schematics
RUN npm run synchronize-lazy-components -- --ci
EXPOSE 8080
CMD npx ng serve --port 8080
