const assert = require('node:assert/strict');
const { readFileSync } = require('node:fs');
const { it } = require('node:test');

const postcss = require('postcss');

process.env.PURGE_CSS = 'true';
const purgeCss = require('../tools/postcss-purgecss-config');

it('preserves Bootstrap tab visibility rules for panels generated by ng-bootstrap', async () => {
  const bootstrap = readFileSync(require.resolve('bootstrap/dist/css/bootstrap.css'), 'utf8');
  const { root } = await postcss([
    purgeCss({
      content: [{ raw: '<nav class="nav-tabs" ngbNav></nav><div [ngbNavOutlet]="nav"></div>', extension: 'html' }],
    }),
  ]).process(bootstrap, { from: undefined });

  const displays = new Map();
  root.walkRules(rule => {
    rule.walkDecls('display', declaration => displays.set(rule.selector, declaration.value));
  });

  assert.equal(displays.get('.tab-content > .tab-pane'), 'none');
  assert.equal(displays.get('.tab-content > .active'), 'block');
  assert.equal(displays.has('.d-none'), false);
});
