variables:
  # Resource group for AKS-cluster
  ResourceGroupName: example
  # Name for registry (<RegistryName>.azurecr.io)
  RegistryName: yourregistry
  # Name of your AKS-cluster
  ClusterName: example
  # K8S namespace for helm deployments
  Namespace: default
  # version for tagging pwa_main
  version_pwa-main: '$(Build.BuildID)'
  # version for tagging pwa_nginx
  version_pwa-nginx: '$(Build.BuildID)'
  # ServiceConnection (Azure Resource Manager)
  AzureSubscription: AzureSubscription
  # Hostname of your ICM installation
  UpstreamICMHost: icm.example.com
  # Ingress host name for pwa-main
  PWAMainHost: pwa.example.com
  # Ingress host name for pwa-nginx
  PWANginxHost: pwa-nginx.example.com
  # ImageName pwa-main
  ImagePWAMain: pwa-main
  # ImageName pwa-nginx
  ImagePWANginx: pwa-nginx

jobs:
  - job: 'BuildAndInstallPWA'
    timeoutInMinutes: 60
    condition: true

    pool:
      vmImage: ubuntu-16.04

    steps:
      - task: Docker@0
        condition: true
        displayName: 'Build $(ImagePWAMain)'
        inputs:
          azureSubscription: $(AzureSubscription)

          azureContainerRegistry: '$(RegistryName).azurecr.io'

          dockerFile: '$(Build.Repository.LocalPath)/Dockerfile'

          imageName: '$(ImagePWAMain):$(version_pwa-main)'

      - task: Docker@0
        condition: true
        displayName: 'Push $(ImagePWAMain)'
        inputs:
          azureSubscription: $(AzureSubscription)

          azureContainerRegistry: '$(RegistryName).azurecr.io'

          action: 'Push an image'

          imageName: '$(ImagePWAMain):$(version_pwa-main)'

      - task: Docker@0
        condition: true
        displayName: 'Build $(ImagePWANginx)'
        inputs:
          azureSubscription: $(AzureSubscription)

          azureContainerRegistry: '$(RegistryName).azurecr.io'

          dockerFile: '**/nginx/Dockerfile'

          imageName: '$(ImagePWANginx):$(version_pwa-nginx)'

      - task: Docker@0
        condition: true
        displayName: 'Push $(ImagePWANginx)'
        inputs:
          azureSubscription: $(AzureSubscription)

          azureContainerRegistry: '$(RegistryName).azurecr.io'

          action: 'Push an image'

          imageName: '$(ImagePWANginx):$(version_pwa-nginx)'

      - task: HelmInstaller@0
        displayName: 'Install Helm'

      - task: HelmDeploy@0
        displayName: 'helm init'
        inputs:
          azureSubscription: $(AzureSubscription)

          azureResourceGroup: '$(ResourceGroupName)'

          kubernetesCluster: $(ClusterName)

          command: init

          arguments: '--service-account tiller'

      - task: HelmDeploy@0
        condition: true
        displayName: 'Install pwa-main'
        inputs:
          azureSubscription: $(AzureSubscription)

          azureResourceGroup: '$(ResourceGroupName)'

          kubernetesCluster: $(ClusterName)

          namespace: '$(Namespace)'

          command: upgrade

          chartType: FilePath

          chartPath: '**/charts/pwa-main'

          releaseName: 'pwa-main-$(Namespace)'

          overrideValues: 'image.repository=$(RegistryName).azurecr.io/$(ImagePWAMain),image.tag=$(version_pwa-main),upstream.icm=https://$(UpstreamICMHost),ingress.hosts[0]=$(PWAMainHost)'

      - task: HelmDeploy@0
        condition: true
        displayName: 'Install pwa-nginx'
        inputs:
          azureSubscription: $(AzureSubscription)

          azureResourceGroup: '$(ResourceGroupName)'

          kubernetesCluster: $(ClusterName)

          namespace: '$(Namespace)'

          command: upgrade

          chartType: FilePath

          chartPath: '**/charts/pwa-nginx'

          releaseName: 'pwa-nginx-$(Namespace)'

          overrideValues: 'image.repository=$(RegistryName).azurecr.io/$(ImagePWANginx),image.tag=$(version_pwa-nginx),upstream.icm=http://$(UpstreamICMHost),upstream.pwa=http://pwa-main-$(Namespace):4200,ingress.hosts[0]=$(PWANginxHost)'
