#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

if git diff-tree -r --name-only --no-commit-id $1 $2 | grep -q package.json
then
  if [ -z "$INTERSHOP_PWA_AUTO_INSTALL" ]
  then
    echo
    echo --------------------------------------------------------------------------------
    echo The \'package.json\' contains changes. It could be necessary to run \'npm install\'.
    echo You can automate this by setting INTERSHOP_PWA_AUTO_INSTALL to "true".
    echo --------------------------------------------------------------------------------
    echo
  fi

  if [ "$INTERSHOP_PWA_AUTO_INSTALL" = "true" ]
  then
    npm install
  fi
fi
