name: Update (Automated)

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - scripts/update-pwa.js

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  AutomatedUpdate:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - uses: actions/checkout@v4
        if: github.ref != 'refs/heads/develop'
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: actions/checkout@v4
        if: github.ref == 'refs/heads/develop'
        with:
          ref: develop

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: package.json
          cache: npm

      - name: Create Update Branch
        run: |
          git config --global user.email "pwa@intershop.de"
          git config --global user.name "GitHub CI"
          git switch -c update/automated-update

      - name: Run Update Script
        run: node scripts/update-pwa

      - name: Run Automated Fixes
        run: |
          npm run lint -- --fix
          npm run format
          git add .
          git commit -m "chore: post update fixes" --allow-empty

      - name: Run Tests
        run: npm run test

      - name: Push Update Branch
        if: always()
        run: git push --force origin update/automated-update
