name: Synchronize develop branch

on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  CancelPrevious:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Old Pipeline
        uses: rokroskar/workflow-run-cleanup-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  Build:
    needs: CancelPrevious
    if: ${{ github.event.repository.owner.login == 'intershop' }}
    runs-on: ubuntu-latest
    steps:
      - name: Azure Pipelines Action
        uses: Azure/pipelines@v1
        with:
          # Fullyqualified URL to the Azure DevOps organization along with project name(eg, https://dev.azure.com/organization/project-name or https://server.example.com:8080/tfs/DefaultCollection/project-name)
          azure-devops-project-url: https://dev.azure.com/ish-pwa-rngrx/intershop-pwa
          # Name of the Azure Pipline to be triggered
          azure-pipeline-name: Sync
          # Paste personal access token of the user as value of secret variable:AZURE_DEVOPS_TOKEN
          azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
