name: Dead Code (Testbed)

on:
  workflow_dispatch:
  # schedule:
  #   # every sunday at midnight
  #   - cron: '0 0 * * 0'

jobs:
  TestBed:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: package.json
          cache: npm

      - name: Install root dependencies
        run: npm ci

      - name: Find Unused TestBed declarations
        run: npm exec npm-run-all cleanup-testbed check-no-changes
