name: DeadCode

on:
  workflow_dispatch:
  schedule:
    # every sunday at midnight
    - cron: '0 0 * * 0'

env:
  NODE_VERSION: 16.16.0

jobs:
  TestBed:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install root dependencies
        run: npm ci

      - name: Find Unused TestBed declarations
        run: npm exec npm-run-all cleanup-testbed check-no-changes
