name: Demo Server (remove)

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed

env:
  AZURE_DEMO_RESOURCEGROUP: pwa-gh-review

jobs:
  RemoveDemoServer:
    if: github.event.repository.full_name == 'intershop/intershop-pwa'
    runs-on: ubuntu-latest
    steps:
      - name: Determine App Names
        run: |
          if [[ -n "${{ github.event.pull_request.head.ref }}" ]]
          then
            REF=${{ github.event.pull_request.head.ref }}
          else
            REF=${{ github.event.ref }}
          fi
          REF=$( echo $REF | sed -e 's/refs\/heads\///' | sed -e 's/[^a-zA-Z0-9-]/-/g' )
          APP_NAME=$(printf '%.60s' "${{ env.AZURE_DEMO_RESOURCEGROUP }}-$REF")
          echo "APP_NAME=$APP_NAME" >> $GITHUB_ENV
      - name: Login to Azure
        run: az login --service-principal --username ${{ secrets.AZURE_SP_USERNAME }} --password ${{ secrets.AZURE_SP_PASSWORD }} --tenant ${{ secrets.AZURE_SP_TENANT }}

      - name: Remove containerized WebApp
        env:
          APP: '${{ env.AZURE_DEMO_RESOURCEGROUP }}-${{ github.event.pull_request.number }}'
          GROUP: ${{ env.AZURE_DEMO_RESOURCEGROUP }}
        run: test -z "$(az webapp show -g $GROUP -n $APP_NAME)" || az webapp delete -g $GROUP --name $APP_NAME
