name: Integration

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - '**.md'
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

env:
  NODE_VERSION: 22.17.1
  NODE_OPTIONS: --max_old_space_size=10240
  ICM_BASE_URL: https://review.icm.intershop.de

jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      TESTING: true

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install root dependencies
        run: npm ci

      - name: Disable ServiceWorker
        run: node schematics/customization/service-worker false

      - name: Build SSR
        run: npm run build:multi

      - name: Upload Build Output
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  Cypress:
    needs: [Build]
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        test: ['b2c']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install e2e dependencies
        run: cd e2e && npm i

      - name: Download Build Output
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Set Environment
        run: |
          echo "PWA_BASE_URL=http://localhost:4200" >> $GITHUB_ENV
          echo "LOGGING=true" >> $GITHUB_ENV
          echo "BROWSER=chrome" >> $GITHUB_ENV

      - name: Set B2C Environment
        if: matrix.test == 'b2c'
        run: |
          echo "THEME=b2c" >> $GITHUB_ENV

      - name: Set B2B Environment
        if: matrix.test == 'b2b'
        run: |
          echo "THEME=b2b" >> $GITHUB_ENV

      - name: Start SSR
        run: |
          node dist/$THEME/run-standalone &

      - name: Cypress
        uses: cypress-io/github-action@v6
        with:
          install: false
          wait-on: 'http://localhost:4200'
          wait-on-timeout: 180
          working-directory: e2e
          command: npx ts-node cypress-ci-e2e **/*handling.b2c*.e2e-spec.ts

      - name: Upload Screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: screenshots_${{ matrix.test }}
          path: e2e/cypress/screenshots

      - name: Upload Videos
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: videos_${{ matrix.test }}
          path: e2e/cypress/videos
