name: Mark Conflicts

on:
  workflow_dispatch:
  push:
    branches:
      - develop
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: eps1lon/actions-label-merge-conflict@v3
        with:
          dirtyLabel: 'has conflicts'
          repoToken: ${{ secrets.GITHUB_TOKEN }}
